Added render mode in simulatiion scene
firecell-engineers/firecell pull request #14
Opened 2022-09-19 20:31 UTC by Tluszczyk

2022-09-19 21:28 UTC, koszar91 requested changes
Looks good, just naming convention to be changed

2022-09-19 21:28 UTC, koszar91 commented on src/main/java/pl/edu/agh/firecell/renderer/BasicRenderer.java
> +    private RenderMode mode = RenderMode.Normal;
```suggestion
    private RenderMode renderMode = RenderMode.Normal;
```

2022-09-19 21:28 UTC, koszar91 commented on src/main/java/pl/edu/agh/firecell/renderer/BasicRenderer.java
> +        this.mode = mode;
```suggestion
        this.renderMode = mode;
```

2022-09-19 21:28 UTC, koszar91 commented on src/main/java/pl/edu/agh/firecell/renderer/RenderMode.java
> +    Normal, Air_Temperature, Solid_Temperature
```suggestion
    NORMAL, 
    AIR_TEMPERATURE,
    SOLID_TEMPERATURE
```
That's convetion in Java

2022-09-20 16:22 UTC, koszar91 approved these changes
GG
Edit: checks :p

2022-09-27 18:22 UTC, Kamil153 requested changes

2022-09-27 18:22 UTC, Kamil153 commented on src/main/java/pl/edu/agh/firecell/core/SimulationScene.java
> +                    renderer.setRenderMode(RenderMode.Normal);
RenderMode values should be uppercase

2022-09-27 18:22 UTC, Kamil153 commented on src/main/java/pl/edu/agh/firecell/renderer/BasicRenderer.java
> +    private RenderMode renderMode = RenderMode.Normal;
It should be `RenderMode.NORMAL` (uppercase)

2022-09-28 14:23 UTC, merged