[FIRE-44] State builder UI
firecell-engineers/firecell pull request #25
Opened 2022-11-08 19:21 UTC by Kamil153

2022-11-08 19:59 UTC, koszar91 commented
Conflicts!

2022-11-08 20:01 UTC, koszar91 commented
Conflicts!

2022-11-13 11:01 UTC, koszar91 commented
My rooms are always failing to load.
I build simple two rooms with a door (air gap) on their common wall. Then I hit save, and then try to run simulation or edit the room, and it's not working, and in the logs I see: `2022-11-13 11:59:25 ERROR RoomStorage : Failed to load room "tomek2"`

2022-11-13 11:03 UTC, koszar91 commented
Bug 2
When I don't give a name to the scene (or first element in the scene, I'm not sure) the app crashes with this error log:
```
Dear ImGui Assertion Failed: id != window->ID && "Cannot have an empty ID at the root of a window. If you need an empty label, use ## and read the FAQ about how the ID Stack works!"
Assertion Located At: /tmp/imgui/jni/imgui.cpp:8412
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Thread.java:1380)
	at imgui.ImGui$1.imAssertCallback(ImGui.java:85)
	at imgui.assertion.ImAssertCallback.imAssert(ImAssertCallback.java:21)
	at imgui.ImGui.selectable(Native Method)
	at pl.edu.agh.firecell.core.statebuilder.StateBuilderScene.renderEditMenu(StateBuilderScene.java:90)
	at pl.edu.agh.firecell.core.statebuilder.StateBuilderScene.renderGUI(StateBuilderScene.java:67)
	at pl.edu.agh.firecell.core.statebuilder.StateBuilderScene.update(StateBuilderScene.java:62)
	at pl.edu.agh.firecell.core.Window.run(Window.java:87)
	at pl.edu.agh.firecell.FirecellApplication.main(FirecellApplication.java:17)
```

2022-11-13 11:04 UTC, koszar91 commented
Issue 1
I cannot ignite anything, I can't find this option in editor.

2022-11-13 11:06 UTC, koszar91 commented
Issue 2
The ImGUI windows are kind of hard to read when you start the application:
![image](https://user-images.githubusercontent.com/72392522/201518503-65d9a07a-9ac3-4c4c-9bd5-8a9f1bf18fe0.png)
Idk what's going on here. Please reorganize them.

2022-11-13 11:07 UTC, koszar91 commented
Issue 3
It would be great if you delete the windows at all :P
And move the whole UI to the top bar, for the user to click on option in this top bar, and the sub-menu appears, for example form for adding elements.

2022-11-13 11:09 UTC, koszar91 requested changes
Functionality looks really great 💪 💪 💪  
But we still need some polishing to the UI and bugfixing :c

2022-11-14 21:52 UTC, Kamil153 commented
> Bug 2 When I don't give a name to the scene (or first element in the scene, I'm not sure) and try to save or add element, the app crashes with this error log:
> 
> ```
> Dear ImGui Assertion Failed: id != window->ID && "Cannot have an empty ID at the root of a window. If you need an empty label, use ## and read the FAQ about how the ID Stack works!"
> Assertion Located At: /tmp/imgui/jni/imgui.cpp:8412
> java.lang.Exception: Stack trace
> 	at java.base/java.lang.Thread.dumpStack(Thread.java:1380)
> 	at imgui.ImGui$1.imAssertCallback(ImGui.java:85)
> 	at imgui.assertion.ImAssertCallback.imAssert(ImAssertCallback.java:21)
> 	at imgui.ImGui.selectable(Native Method)
> 	at pl.edu.agh.firecell.core.statebuilder.StateBuilderScene.renderEditMenu(StateBuilderScene.java:90)
> 	at pl.edu.agh.firecell.core.statebuilder.StateBuilderScene.renderGUI(StateBuilderScene.java:67)
> 	at pl.edu.agh.firecell.core.statebuilder.StateBuilderScene.update(StateBuilderScene.java:62)
> 	at pl.edu.agh.firecell.core.Window.run(Window.java:87)
> 	at pl.edu.agh.firecell.FirecellApplication.main(FirecellApplication.java:17)
> ```

I've created separate story for input validation. I've added default room and element names for now.

2022-11-19 11:12 UTC, koszar91 requested changes
Absolute perfection. Good job! Just fix one thing and resolve conflicts with develop (if needed) and we can merge

2022-11-19 11:12 UTC, koszar91 commented on src/main/java/pl/edu/agh/firecell/core/statebuilder/element/IgnitionElement.java
> +                    cells.set(index, new Cell(400, 1, oldCell.flammable(),
Here you set an arbitrary start temperature. That's wrong, take it from the material of the cell.

2022-11-19 15:32 UTC, koszar91 approved these changes
GG 💪

2022-11-19 15:33 UTC, merged